### ISSUE TITLE
Add null-safety support

### ISSUE THREAD

**Issue by raulmabe** [afkcodes/flutter_phosphor_icons#1]
Cool package! Would be awesome to [migrate it to null-safety](https://dart.dev/null-safety/migration-guide#:~:text=The%20migration%20tool%20takes%20a,release%20of%20the%20Dart%20SDK.)

**Comment by afkcodes** [comment]
yes @raulmabe i will be doing this also tried doing it but seems that there was no marginal changes, currently i'm busy with some stuff once that finishes will do this asap. Thanks for using the package.

**Comment by raulmabe** [comment]
Made a PR #2!
