### ISSUE TITLE
Icondata is wrong in null safe new version

### ISSUE THREAD

**Issue by ghost** [afkcodes/flutter_phosphor_icons#4]
These is issue with null safe package. Icons do not match with Icondata input .

e.g. PhosphorIcons.heart_light  shows different icons
![photo_2021-03-17_16-57-15](https://user-images.githubusercontent.com/77090711/111460636-38795880-8742-11eb-942d-bd4a401bd23e.jpg)

**Comment by afkcodes** [comment]
@drmspatil  Did you run the example app, i just ran it and it seems its rendering correctly for me.

**Comment by ghost** [comment]
Now its working fine . Must be some glitch with flutter clean .

**Comment by afkcodes** [comment]
cool @drmspatil closing this then.
